### ISSUE TITLE
Remove Mina circuit logic to separate repository

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/proof-producer#2]
We have Mina circuit logic deep inside the proof producer algorithm. It shouldn't be like that - we need to move this circuit to https://github.com/NilFoundation/mina-state-proof repository.

We also need to check, if Mina state proof is compatible with latest marshalling versions. If it's not, then we can not process it as an input for proof producer.

**Comment by nemothenoone** [comment]
Just in case, Mina's repository now features relevant directory for circuits: https://github.com/NilFoundation/mina-state-proof/tree/master/circuits

**Comment by nkaskov** [comment]
I believe this one is finished. If we ever need Mina circuits, we can take them from proof-producer's commit history.
