### ISSUE TITLE
[Feature request]: comprehensible log messages from the multithreaded proof producer

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/proof-producer#35]
We recently faced an issue with the multithreaded version (https://github.com/NilFoundation/proof-producer/issues/33), in which the error message resulted being 
```bash
proof-generator-multithreaded: /opt/boost/boost/include/boost/container/pmr/polymorphic_allocator.hpp:58: boost::container::pmr::polymorphic_allocator<T>::polymorphic_allocator(boost::container::pmr::memory_resource*) [with T = char]: Assertion `r != 0' failed.
Aborted (core dumped) 
```

We need to handle the errors and assertions in `Release` mode to make it clear to the user. The best way to do it seems to be adding different log-level messages with Boost log2 (as we use it already in this repository and in the others).

**Comment by x-mass** [comment]
Regarding assertions, they will be omitted from Release build anyway. We should replace them with errors, if we want to have a trace or handle them in caller.
All exceptions would be forwarded to Boost logger in refactored code [here](https://github.com/NilFoundation/proof-producer/blob/9916a657c03c4a302cb49a0c7cd7e94bd869b968/bin/proof-generator/src/main.cpp#L59-L62)
