### ISSUE TITLE
Issue building proof-generator-multi-threadedfrom source

### ISSUE THREAD

**Issue by Robertorosmaninho** [NilFoundation/proof-producer#82]
Trying to build from source the project on Ubuntu Jammy I got the following error:

Error message: https://gist.github.com/Robertorosmaninho/1b97011cac962eb3a598d921c19ffc97

(The error message was too big to fit the issue requirements.)

**Comment by martun** [comment]
We have moved to nix now, and the error must be gone. Please re-open if it fails again.
